image:
  - Visual Studio 2019
clone_folder: c:\projects\source
build_script:
  - cmd: >-
      mkdir build

      cd build

      pip install --user conan

      set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Scripts
      set PATH=%PATH%;C:\Qt\5.14.2

      cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PREFIX_PATH=c:/Qt/5.14.2

      cmake --build . --config "Release"

test_script:
  - cmd: ctest -C Debug

